# Add your build targets here as you work through the exercises.
#
# Buck2 doesn't have built-in Go rules in the demo toolchain.
# For now, use genrule to shell out to the Go compiler:

genrule(
    name = "gateway",
    srcs = glob(["src/**/*.go"]),
    out = "gateway",
    cmd = "cd $SRCS_DIR/.. && go build -o $OUT ./src/",
    executable = True,
)

genrule(
    name = "bench",
    srcs = glob(["src/**/*.go"]),
    out = "bench",
    cmd = "cd $SRCS_DIR/.. && go build -o $OUT ./src/bench/",
    executable = True,
)
